services:
  nginx:
    init: true
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    networks:
      - code_net
    ports:
      - 443:443
      - 9999:9999
    depends_on:
      - code
    volumes:
      - code_data:/var/lib/nginx/code_data
    restart: on-failure
  code:
    init: true
    container_name: code_server
    build:
      context: ./requirements/code_server/
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/.local:/home/coder/.local
      - ${HOME}/.config:/home/coder/.config
      - ${HOME}:/home/coder/project
    environment:
      - DOCKER_USER=${USER}
    networks:
      - code_net
    ports:
      - 10000:8080
    restart: on-failure

networks:
  code_net:
    name: code_net
    driver: bridge

volumes:
  code_data:
    name: code_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sabyun/code_data
